[package]
name = "todaiji"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "2"

[dev-dependencies]
datatest-stable = "0.3"
assert_cmd = "2.1.1"
tempfile = "3.23.0"
insta = "1.44.1"

[[test]]
name = "cli"
harness = false
